pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        checkout scm
        sh 'ls -al'
        sh 'mvn clean install'
      }
    }
  }
}   
